### ISSUE TITLE
I have no idea how Git works haha

### ISSUE THREAD

**Issue by TheAwesomeGuy** [kylethielk/twitter-findtofollow#2]
Please help me set this up. Have no idea where to start what so ever.

**Comment by kylethielk** [comment]
Hi @TheAwesomeGuy . You will need a web server that is capable of running PHP. For windows WAMP(http://www.wampserver.com/en/) is a good place to start or for Mac MAMP( https://www.mamp.info/en/ )

**Comment by TheAwesomeGuy** [comment]
Ahh, I see. Thanks, anything else?

**Comment by kylethielk** [comment]
Once you have the server up and running it should be as simple as placing the source code in the root document directory.

**Comment by TheAwesomeGuy** [comment]
Okay thanks Kyle, will let you know if I get stuck. :)
