### ISSUE TITLE
There was an error authorizing you via Twitter, please try again.

### ISSUE THREAD

**Issue by cmdrfletcher** [kylethielk/twitter-findtofollow#3]
Hello Kyle,

I want to try your script, but when I enter my "consumer_key" / "consumer_secret" and point my browser to the installation, the only message which appear is:

_There was an error authorizing you via Twitter, please try again._

Maybe you can give me a hint what to do?

Greetings,
Patrick

**Comment by davkap92** [comment]
Hey cmdrfletcher,
Had the exact same issue, was to do with the callback url in my twitter app
being blank, so twitter treats it as a desktop app.
Found the answer here: http://stackoverflow.com/questions/3828793/twitter-oauth-geting-undefined-index-oauth-token-secret-in/23196802#23196802

Seems to be working fine after that

**Comment by kylethielk** [comment]
Thanks very much @davkap92 for replying!
